add_executable(resolve)
target_sources(resolve PRIVATE "main.cpp" "ares_resolver.cpp" "tls_transport.cpp" "utils.cpp")
target_link_libraries(resolve PRIVATE Threads::Threads)
target_link_libraries(resolve PRIVATE Boost::program_options)
target_link_libraries(resolve PRIVATE spdlog::spdlog_header_only)
target_link_libraries(resolve PRIVATE c-ares::cares)
target_link_libraries(resolve PRIVATE OpenSSL::SSL OpenSSL::Crypto)
